### ISSUE TITLE
Add threads to the simple server example

### ISSUE THREAD

**Issue by yoid2000** [gda-score/anon-methods#9]
Please add or enable threading at the server. Some queries may take some time and will block. Probably flask has this built in, so maybe just needs to be enabled. If so please do it. If not please implement this with threads so that more than one request can be handled in parallel.

**Comment by rbh-93** [comment]
Hi,
I have made the server multithreaded. The change can be viewed in simpleServer.py There is another option of making it handle each request as a separate process. The number of processes has to be specified so that it can handle each request in a new process up to this maximum number of concurrent processes. If you want that I can do that instead of setting "threaded=True" (this basically states that it handles each request in a separate thread).

**Comment by rbh-93** [comment]
I also added a few exception handling in simpleClient.py, because I thought it would be a good idea in case problems arise in Client-Server connection in future. I included some exceptions which I think might arise in Client-Server connection.  Please review the changes and let me know if everything is alright.

**Comment by rbh-93** [comment]
I also added exception handling in simpleClient.py, because I thought it would be a good idea in case problems arise in Client-Server connection in future. I added some common exceptions which I think can arise in Client-Server connection.  Please review the changes and let me know if everything is alright.

**Comment by yoid2000** [comment]
Looks fine for now. I'll close, and if there are issues in using the code, we can come back to it.
